
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prdigma
 */
public class ujikebolehan extends javax.swing.JFrame {
    String temp= "";
    Double ti, bt, h1; 
    /**
     * Creates new form ujikebolehan
     */
    public ujikebolehan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        saran = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbperempuan = new javax.swing.JRadioButton();
        rblaki = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        tftinggi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfbb = new javax.swing.JTextField();
        btnKeluar = new javax.swing.JButton();
        btnCobaLagi = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        kideal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 40, 70, 30);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel10.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(110, 270, 160, 30);
        getContentPane().add(saran);
        saran.setBounds(40, 350, 270, 40);
        getContentPane().add(hasil);
        hasil.setBounds(40, 300, 270, 40);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(null);

        rbperempuan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        rbperempuan.setText("Perempuan");
        rbperempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbperempuanActionPerformed(evt);
            }
        });
        jPanel1.add(rbperempuan);
        rbperempuan.setBounds(130, 160, 100, 30);

        rblaki.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        rblaki.setText("Laki-Laki");
        jPanel1.add(rblaki);
        rblaki.setBounds(240, 160, 80, 30);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setText("Jenis Kelamin");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 160, 100, 30);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("Berat Badan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 120, 90, 30);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("Tinggi ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 80, 50, 30);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setText("CEK TUBUH IDEAL ANDA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 170, 30);

        tfnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamaActionPerformed(evt);
            }
        });
        jPanel1.add(tfnama);
        tfnama.setBounds(130, 40, 190, 30);

        tftinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftinggiActionPerformed(evt);
            }
        });
        jPanel1.add(tftinggi);
        tftinggi.setBounds(130, 80, 130, 30);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 80, 34, 20);

        jLabel6.setText("kg");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 120, 40, 20);

        tfbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbbActionPerformed(evt);
            }
        });
        jPanel1.add(tfbb);
        tfbb.setBounds(130, 120, 130, 30);

        btnKeluar.setBackground(new java.awt.Color(255, 255, 51));
        btnKeluar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar);
        btnKeluar.setBounds(250, 200, 71, 30);

        btnCobaLagi.setBackground(new java.awt.Color(255, 255, 51));
        btnCobaLagi.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnCobaLagi.setText("Coba Lagi");
        btnCobaLagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobaLagiActionPerformed(evt);
            }
        });
        jPanel1.add(btnCobaLagi);
        btnCobaLagi.setBounds(130, 200, 110, 30);

        btnHitung.setBackground(new java.awt.Color(255, 255, 51));
        btnHitung.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btnHitung);
        btnHitung.setBounds(40, 200, 70, 30);

        jLabel9.setText("kg");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(290, 250, 34, 20);

        kideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kidealActionPerformed(evt);
            }
        });
        jPanel1.add(kideal);
        kideal.setBounds(220, 240, 60, 30);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setText("Berat badan ideal anda adalah");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 240, 190, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 370, 400);

        setBounds(0, 0, 385, 445);
    }// </editor-fold>//GEN-END:initComponents

    private void kidealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kidealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kidealActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tfbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfbbActionPerformed

    private void tfnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnamaActionPerformed

    private void rbperempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbperempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbperempuanActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        if(tfbb.getText().equals("")||tftinggi.getText().equals("")||tfnama.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Kotak isian harus diisi terlebih dahulu");} 
        else if(rblaki.isSelected()||rbperempuan.isSelected()){
            try {
                Proses();
            } 
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Inputan Ada yang salah!");
            }
        }  
        else {
                    JOptionPane.showMessageDialog(null, "Jenis Kelamin silahkan diisi");
                    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnCobaLagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobaLagiActionPerformed
            saran.setText("");
            hasil.setText("");
            kideal.setText("");
            rbperempuan.setSelected(false);
            rblaki.setSelected(false);
            tfnama.setText("");
            tftinggi.setText("");
            tfbb.setText("");
            buttonGroup1.clearSelection();        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCobaLagiActionPerformed

    private void tftinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftinggiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ujikebolehan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobaLagi;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kideal;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tfbb;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tftinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.valueOf(tftinggi.getText());
        bt = Double.valueOf(tfbb.getText());
        
        if (rbperempuan.isSelected()){
            h1 = (ti - 110 ) * 1;
        } else if (rblaki.isSelected()){
            h1 = (ti - 104 ) * 1;
        } 
        temp = Double.toString(h1.intValue());
        
        if (h1 <  bt){
            kideal.setText(temp);
            hasil.setText("Maaf" + tfnama.getText() + ", Sepertinya anda Overweight :(");
            saran.setText("Banyaklah berolah raga dan hindari makanan yang berkolesterol serta jaga pola makan anda");
        } else if (h1 > bt){
            kideal.setText(temp);
            hasil.setText("Maaf" + tfnama.getText() + ", Sepertinya anda Underweight :(");
            saran.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat serta banyaklah minum air putih");
        } else{
            kideal.setText(temp);
            hasil.setText("Selamat" + tfnama.getText() + ", Berat badan anda sudah ideal :(");
            saran.setText("Lnanjutkab pola makan teratur dan gaya hidup sehat anda");
        }
    }
}
